# Read the Docs configuration file

version:    2

build:
  # Avoid complaints about old OpenSSL 
  os: ubuntu-22.04
  tools:
    python: '3.10'

python:
  install:
    - path:     .
      extra_requirements:
        - docs


