# Notification of changes

name: Notify

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: fateyan/action-discord-notifier@v1
        with:
          message-title: ${{ github.repository }} updated
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
